# Generated by Django 5.1.7 on 2025-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_comment_delete_ticketcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
